services:
  backend:
    container_name: three-monkeys-backend
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    container_name: three-monkeys-frontend
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
